/**
 * TEMP bench API for the commentary replay runs (scripts/replay-commentary.ts).
 * GET  /api/replay-commentary            → list of runs (newest first)
 * GET  /api/replay-commentary?run=<name> → one run's full payload
 * Read-only over data/replay-commentary/*.json — no DB, no external calls.
 */
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { NextResponse } from 'next/server';
import { adminOnly } from '@/lib/auth/server';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

const DIR = join(process.cwd(), 'data', 'replay-commentary');

export async function GET(req: Request) {
  const denied = adminOnly(req);
  if (denied) return denied;
  try {
    const url = new URL(req.url);
    const run = url.searchParams.get('run');
    if (run) {
      // Names are generated by the bench script — allow only its shape.
      if (!/^run-[\w.-]+$/.test(run)) return NextResponse.json({ error: 'bad run name' }, { status: 400 });
      const raw = readFileSync(join(DIR, `${run}.json`), 'utf8');
      return NextResponse.json({ success: true, run: JSON.parse(raw) });
    }
    let names: string[] = [];
    try {
      names = readdirSync(DIR).filter((f) => f.startsWith('run-') && f.endsWith('.json'));
    } catch {
      // directory absent until the first bench run — empty list, not an error
    }
    const entries = names.map((f) => {
      const p = join(DIR, f);
      const j = JSON.parse(readFileSync(p, 'utf8')) as {
        runName: string;
        date: string;
        label: string;
        createdAt: string;
        dry: boolean;
        metrics: unknown;
      };
      return {
        mtime: statSync(p).mtimeMs,
        data: {
          runName: j.runName,
          date: j.date,
          label: j.label,
          createdAt: j.createdAt,
          dry: j.dry,
          metrics: j.metrics,
        },
      };
    });
    entries.sort((a, b) => b.mtime - a.mtime);
    return NextResponse.json({
      success: true,
      runs: entries.map((e) => e.data),
    });
  } catch (e) {
    return NextResponse.json({ success: false, error: (e as Error).message }, { status: 500 });
  }
}
